package com.vline.helper

object ApiContants {

//        const val PREF_base_url = "http://cbisolar.in/cbipanel/Api/Api/"
//        const val PREF_base_url = "http://ec2-18-233-135-9.compute-1.amazonaws.com:8000/api/v1/"
//        const val PREF_base_url = "http://ec2-18-233-135-9.compute-1.amazonaws.com:9000/api/v1/"
        const val PREF_base_url = "https://vline.webpino.tech/api/"

        const val PREF_customer_login = "register"
        const val PREF_login = "login"
        const val PREF_AddNkk = "AddNkk"
        const val PREF_updateNkk = "updateNkk"
        const val PREF_viewshakhauser = "viewshakhauser"
        const val PREF_searchSS = "searchSS"
        const val PREF_viewuser = "viewuser"
        const val PREF_viewNkk = "NagerK"
        const val PREF_deletess = "deletess"
        const val PREF_dashboard = "dashboard"
        const val PREF_getExcel = PREF_base_url + "getExcel"
        const val PREF_attandance = "attandance"
        const val PREF_profileupdate = "profileupdate"
        const val PREF_passwordchange = "passwordchange"
        const val PREF_StoreList = "store"
        const val PREF_notification = "notification"
        const val PREF_product_list = "product_list"
        const val PREF_banner_list = "banner_list"
        const val PREF_ser_req_status = "ser_req_status"
        const val PREF_winner_list = "winner_list"
        const val PREF_privacypolicy = "https://www.rss.org/"

        const val PREF_GET_NKK = "NagerK"

        const val shakhaDetails = "shakhaDetails"
        const val daitva = "daitva"

        const val PREF_getNkkDoc = PREF_base_url + "getNkkDoc"

        const val PREF_UserAPI = "userAPI"
        const val PREF_ClinicAPI = "clinicAPI"
        const val PREF_new_prospect = "new_prospect"
        const val PREF_appointmentAPI = "appointmentAPI"

        const val id = "id"
        const val login = "login"
        const val isMskUser = "isMskUser"
        const val isDeleted = "isDeleted"

        const val PREF_USER_NAME= "PREF_USER_NAME"
        const val PREF_F_name = "PREF_F_name"
        const val PREF_L_name = "PREF_L_name"
        const val PREF_WhatsAppNumber = "PREF_L_name"
        const val PREF_USER_ID = "USER_ID"
        const val PREF_Token = "Token"
        const val PREF_USER_SHAKA = "USER_SHAKA"
        const val PREF_STATUS = "PREF_STATUS"
        const val PREF_role = "PREF_role"
        const val PREF_nager = "PREF_nager"

        const val PREF_city = "city"
        const val PREF_pin = "pin"
        const val PREF_providername = "providername"
        const val PREF_registration = "registration"
        const val PREF_error_message = "error_message"
        const val PREF_providerid = "providerid"
        const val PREF_longitude = "longitude"
        const val PREF_st = "st"
        const val PREF_cell = "cell"
        const val PREF_type = "type"
        const val PREF_practiceaddress = "practiceaddress"
        const val PREF_result = "result"
        const val PREF_provider = "provider"
        const val PREF_latitude = "latitude"
        const val PREF_practicename = "practicename"
        const val PREF_locationurl = "locationurl"
        const val PREF_error_code = "error_code"
        const val PREF_email = "email"

        const val PREF_IsLogin = "PREF_IsLogin"
        const val PREF_ref_code = "PREF_ref_code"
        const val PREF_clinic_count = "PREF_clinic_count"
        const val PREF_ref_id = "PREF_ref_id"
        const val PREF_prospectid = "PREF_prospectid"
        const val PREF_totaldownline = "PREF_totaldownline"
        const val PREF_AMOUNT = "Loan_amount"
        const val PREF_totaldirect = "totaldirect"
        const val status1 = "status1"
        const val PREF_device = "PREF_device"
        const val PREF_Address = "PREF_Address"
        const val PREF_Balance = "PREF_Balance"
        const val PREF_operator_code = "PERF_Operoto_code"
        const val PREF_amt = "PREF_amt"
        const val PREF_temp_number = "PREF_temp_number"
        const val PREF_Landmark = "PREF_Landmark"
        const val PREF_CountryCode = "PREF_CountryCode"
        const val PREF_StateId = "PREF_StateId"
        const val PREF_Zip = "PREF_Zip"
        const val isDisable = "isDisable"

}