package com.vline.helper

object SharedPrefData {

    var PREF_Msrno = "Msrno"
    var PREF_Membertype = "Membertype"
    var PREF_MemberID = "MemberID"
    var PREF_MemberName = "PREF_MemberName"
    var PREF_Mobile = "PREF_Mobile"
    var PREF_TransPass = "PREF_TransPass"
    var user_code = "user_code"
    var PREF_IsLogin = "PREF_IsLogin"
    var PREF_user_image = "PREF_user_image"
    var PREF_Login_Id = "PREF_Login_Id"
    var PREF_Login_password = "PREF_Login_password"
    var PREF_email = "email"
    var PREF_join_date = "PREF_join_date"
    var PREF_city = "city"
    var PREF_state = "state"
    var PREF_totaldownline = "totaldownline"
    var PREF_AMOUNT = "Loan_amount"
    var PREF_totaldirect = "totaldirect"
    var PREF_device = "PREF_device"
    var PREF_Address = "PREF_Address"
    var PREF_Balance = "PREF_Balance"
    var PREF_operator_code = "PERF_Operoto_code"
    var PREF_amt = "PREF_amt"
    var PREF_temp_number = "PREF_temp_number"
    var PREF_Landmark = "PREF_Landmark"
    var PREF_CountryCode = "PREF_CountryCode"
    var PREF_StateId = "PREF_StateId"
    var PREF_Zip = "PREF_Zip"
    var PREF_GST_no = "PREF_GST_no"
    var PREF_F_name = "PREF_F_name"
    var PREF_L_name = "PREF_L_name"
}
